export const Headings = [
    {
        id:"sno",
        title:"s.no"
    },
    {
        id:"rollno",
        title:"Rollno"
    },
    {
        id:"fullname",
        title:"Name"
    },
    {
        id:"hacker",
        title:"HackerRank"
    },
    {
        id:"leet",
        title:"LeetCode"
    },
    {
        id:"chef",
        title:"CodeChef"
    },
    {
        id:"forces",
        title:"CodeForces"
    },
    {
        id:"interviewbit",
        title:"InterviewBit"
    },
    {
        id:"spoj",
        title:"Spoj"
    },
    {
        id:"total",
        title:"Total"
    }
];